pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: maven
    image: maven:3.9.9-eclipse-temurin-21
    command: ['cat']
    tty: true
    volumeMounts:
    - name: maven-repo
      mountPath: /home/jenkins/.m2
  volumes:
  - name: maven-repo
    emptyDir: {}
"""
    }
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build') {
      steps {
        container('maven') {
          sh 'java -version && mvn -v'
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }

    stage('Test') {
      steps {
        container('maven') {
          sh 'mvn test'
        }
      }
      post {
        always {
          junit 'target/surefire-reports/*.xml'
        }
      }
    }

    stage('Deliver') {
      steps {
        container('maven') {
          sh './jenkins/scripts/deliver.sh'
        }
      }
    }
  }
}
