pipeline {
    agent {
        kubernetes {
        yaml """
    apiVersion: v1
    kind: Pod
    spec:
    serviceAccountName: jenkins
    containers:
    - name: git
        image: alpine/git:2.45.2
        command: ['cat']
        tty: true
    - name: maven
        image: maven:3.9.9-eclipse-temurin-21   # <-- JDK 21
        command: ['cat']
        tty: true
        volumeMounts:
        - name: maven-repo
        mountPath: /home/jenkins/.m2
    volumes:
    - name: maven-repo
        emptyDir: {}
    """
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
